console.log( ' 2 + true  = ', 2 + true );
console.log( ' 2 + false  = ', 2 + false );
console.log( ' 2 + \'\'  = ', 2 + '' );
console.log( ' 2 + \'45\'  = ', 2 + '45' );
console.log( ' 2 + 45  = ', 2 + 45 );
console.log( ' 2 + undefined  = ', 2 + undefined );
console.log( ' 2 + null  = ', 2 + null );
console.log( '2 + {} = ', 2 + {} );
console.log( '2 + Symbol() = ', 2 + Symbol() );